### ISSUE TITLE
Opening more than one diagram causes displaying problems

### ISSUE THREAD

**Issue by ndoschek** [eclipse-emfcloud/ecore-glsp#86] opened 2021-02-15 09:37 UTC
![ecore-glsp-bug-diagrams](https://user-images.githubusercontent.com/47414588/107929274-b4cd2000-6f79-11eb-8ad5-4f973ef0af3f.gif)

**Comment by CamilleLetavernier** [comment] 2021-02-15 09:48
This is a duplicate of #23

**Closed by CamilleLetavernier** 2021-02-15 09:48 UTC
Labels: diagram
