### ISSUE TITLE
Nodes are not displayed when opening two diagrams

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-emfcloud/ecore-glsp#124] opened 2022-03-11 19:40 UTC
When I open two digrams directly after each other, the node on the second diagram are not displayed, see this screenshot:

![bugvideo](https://user-images.githubusercontent.com/1052615/157945861-bf925e89-7d7b-454f-a8f2-3b3f40731312.gif)

**Comment by JonasHelming** [comment] 2022-03-12 12:41
@CamilleLetavernier

**Comment by ndoschek** [comment] 2022-08-01 07:09
This is a duplicate of https://github.com/eclipse-emfcloud/ecore-glsp/issues/23

**Comment by ndoschek** [comment] 2022-12-01 10:18
This is a duplicate of https://github.com/eclipse-emfcloud/ecore-glsp/issues/23

**Closed by ndoschek** 2022-12-01 10:18 UTC
Labels: bug, duplicate
